[project]
name = "asin-health-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.75",
    "fastapi>=0.135.2",
    "strands-agents>=1.33.0",
    "strands-agents-tools>=0.2.23",
    "uvicorn>=0.42.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.0.2",
]
