apiVersion: v1
kind: Service
metadata:
  name: asin-health-platform
  namespace: asin-health
  labels:
    app: asin-health-platform
spec:
  type: NodePort
  selector:
    app: asin-health-platform
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
